### ISSUE TITLE
Rajouter la classe `fr-table` sur les tables des pages markdown

### ISSUE THREAD

**Issue by maudetes** [etalab/ouverture.data.gouv.fr#39]
We currently have tables looking like:
![image](https://github.com/etalab/ouverture.data.gouv.fr/assets/28541902/5d565bcd-79f6-4fe3-9f5a-ba7f4691640e)

By adding `class="fr-table"`, we would have:
![image](https://github.com/etalab/ouverture.data.gouv.fr/assets/28541902/5347430b-e9bb-40aa-94af-e7593f5495cc)

I don't know if we can add this class automatically in the markdown conf

**Comment by nicolaskempf57** [comment]
Note : pour respecter le dsfr, il faut un `<div class="fr-table">` autour du tableau.

J'imagine qu'il est possible de le faire comme pour [les liens](https://github.com/etalab/udata-front/blob/master/udata_front/theme/gouvfr/assets/js/markdown.js#L16).
